/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeshop;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Ghin
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment(List<Button> mproducts,String mpromoCode, double msubtotal, double mpromo, double mtax, double mtotal) {
        initComponents();
        products = new ArrayList<>();
        for (Button i : mproducts){
            products.add(i);
        }
        promoCode = mpromoCode;
        subtotal = msubtotal;
        promo = mpromo;
        tax = mtax;
        total = mtotal;
        lblPromo.setText(String.valueOf(promo));
        lblSubtotal.setText(String.valueOf(subtotal));
        lblTax.setText(String.valueOf(tax));
        lblTotal.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPromo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpBitcoinPayment = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfBitcoinAmt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbtnSendBTC = new javax.swing.JButton();
        jbtnScanCode = new javax.swing.JButton();
        jlblQRC = new javax.swing.JLabel();
        jpCreditDebit = new javax.swing.JPanel();
        jradCredit = new javax.swing.JRadioButton();
        jradDebit = new javax.swing.JRadioButton();
        jlblCardNum = new javax.swing.JLabel();
        jtfCardNum = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jpGC = new javax.swing.JPanel();
        jlblGiftCardNum = new javax.swing.JLabel();
        jtfGiftCardNum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jpNumPad = new javax.swing.JPanel();
        jbtnNumAmt20 = new javax.swing.JButton();
        jbtnNumAmt10 = new javax.swing.JButton();
        jbtnNum7 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum4 = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNumAmt5 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum0 = new javax.swing.JButton();
        jbtnNumAmtExact = new javax.swing.JButton();
        jbtnNumDot = new javax.swing.JButton();
        jbtnNum9 = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtnNum00 = new javax.swing.JButton();
        jbtnEnter = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jtfNumPad = new javax.swing.JTextField();
        jpPaymentButtons = new javax.swing.JPanel();
        jbtnBitcoin = new javax.swing.JButton();
        jbtnCash = new javax.swing.JButton();
        jbtnGiftCard = new javax.swing.JButton();
        jbtnCreditCard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnPay = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Subtotal:");
        jPanel5.add(jLabel6);

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSubtotal.setText("0.00");
        jPanel5.add(lblSubtotal);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Discount:");
        jPanel5.add(jLabel7);

        lblPromo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPromo.setText("0.00");
        jPanel5.add(lblPromo);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Tax:");
        jPanel5.add(jLabel8);

        lblTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTax.setText("0.00");
        jPanel5.add(lblTax);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Total:");
        jPanel5.add(jLabel10);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setText("0.00");
        jPanel5.add(lblTotal);

        jPanel1.setLayout(new java.awt.CardLayout(5, 5));

        jpBitcoinPayment.setVisible(false);
        jpBitcoinPayment.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Send");

        jLabel11.setText("To");

        jtfBitcoinAmt.setText("                 ");

        jLabel12.setText("BTC");

        jLabel13.setText("23480yskjuLXKueAVck123l032");

        jbtnSendBTC.setText("OK");

        jbtnScanCode.setText("Scan Code");

        jlblQRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/QRC.png"))); // NOI18N
        jlblQRC.setText(" ");
        jlblQRC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpBitcoinPaymentLayout = new javax.swing.GroupLayout(jpBitcoinPayment);
        jpBitcoinPayment.setLayout(jpBitcoinPaymentLayout);
        jpBitcoinPaymentLayout.setHorizontalGroup(
            jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblQRC)
                        .addGap(18, 18, 18)
                        .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)))
                    .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jbtnScanCode, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBitcoinPaymentLayout.createSequentialGroup()
                        .addComponent(jtfBitcoinAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                        .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnSendBTC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(0, 45, Short.MAX_VALUE))))
        );
        jpBitcoinPaymentLayout.setVerticalGroup(
            jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfBitcoinAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addGap(116, 116, 116))
            .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblQRC, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnScanCode)
                    .addComponent(jbtnSendBTC))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jpBitcoinPayment, "card3");

        jpCreditDebit.setVisible(false);
        jpCreditDebit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jradCredit);
        jradCredit.setSelected(true);
        jradCredit.setText("Credit");

        buttonGroup1.add(jradDebit);
        jradDebit.setText("Debit");

        jlblCardNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblCardNum.setText("Card Number");

        jtfCardNum.setText(" ");
        jtfCardNum.setMinimumSize(new java.awt.Dimension(6, 24));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Expiration Date");

        jTextField1.setPreferredSize(new java.awt.Dimension(6, 24));

        jLabel15.setText("MM/YY");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("CCV");

        jTextField2.setPreferredSize(new java.awt.Dimension(6, 24));

        javax.swing.GroupLayout jpCreditDebitLayout = new javax.swing.GroupLayout(jpCreditDebit);
        jpCreditDebit.setLayout(jpCreditDebitLayout);
        jpCreditDebitLayout.setHorizontalGroup(
            jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreditDebitLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradCredit)
                    .addComponent(jlblCardNum)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCreditDebitLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addComponent(jtfCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradDebit)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCreditDebitLayout.setVerticalGroup(
            jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreditDebitLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradDebit)
                    .addComponent(jradCredit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCardNum)
                    .addComponent(jtfCardNum, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCreditDebitLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jpCreditDebitLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addGap(42, 42, 42))
        );

        jPanel1.add(jpCreditDebit, "card4");

        jpGC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpGC.setVisible(false);

        jlblGiftCardNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblGiftCardNum.setText("Gift Card Number");

        jtfGiftCardNum.setText(" ");

        jButton1.setText("Check Balance");

        javax.swing.GroupLayout jpGCLayout = new javax.swing.GroupLayout(jpGC);
        jpGC.setLayout(jpGCLayout);
        jpGCLayout.setHorizontalGroup(
            jpGCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblGiftCardNum)
                .addGap(18, 18, 18)
                .addGroup(jpGCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfGiftCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jpGCLayout.setVerticalGroup(
            jpGCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGCLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jpGCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblGiftCardNum)
                    .addComponent(jtfGiftCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );

        jPanel1.add(jpGC, "card5");

        jpNumPad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpNumPad.setLayout(new java.awt.GridBagLayout());

        jbtnNumAmt20.setText("20.00");
        jbtnNumAmt20.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnNumAmt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumAmt20ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumAmt20, gridBagConstraints);

        jbtnNumAmt10.setText("10.00");
        jbtnNumAmt10.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnNumAmt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumAmt10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumAmt10, gridBagConstraints);

        jbtnNum7.setText("7");
        jbtnNum7.setMaximumSize(null);
        jbtnNum7.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum7, gridBagConstraints);

        jbtnNum8.setText("8");
        jbtnNum8.setMaximumSize(null);
        jbtnNum8.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum8, gridBagConstraints);

        jbtnNum4.setText("4");
        jbtnNum4.setMaximumSize(null);
        jbtnNum4.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum4, gridBagConstraints);

        jbtnNum5.setText("5");
        jbtnNum5.setMaximumSize(null);
        jbtnNum5.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum5, gridBagConstraints);

        jbtnNum1.setText("1");
        jbtnNum1.setMaximumSize(null);
        jbtnNum1.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum1, gridBagConstraints);

        jbtnNumAmt5.setText("5.00");
        jbtnNumAmt5.setMinimumSize(new java.awt.Dimension(59, 23));
        jbtnNumAmt5.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnNumAmt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumAmt5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumAmt5, gridBagConstraints);

        jbtnNum2.setText("2");
        jbtnNum2.setMaximumSize(null);
        jbtnNum2.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum2, gridBagConstraints);

        jbtnNum0.setText("0");
        jbtnNum0.setMaximumSize(null);
        jbtnNum0.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum0, gridBagConstraints);

        jbtnNumAmtExact.setText("Exact");
        jbtnNumAmtExact.setMaximumSize(null);
        jbtnNumAmtExact.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnNumAmtExact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumAmtExactActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumAmtExact, gridBagConstraints);

        jbtnNumDot.setText(".");
        jbtnNumDot.setMaximumSize(null);
        jbtnNumDot.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNumDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumDotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumDot, gridBagConstraints);

        jbtnNum9.setText("9");
        jbtnNum9.setMaximumSize(null);
        jbtnNum9.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum9, gridBagConstraints);

        jbtnNum6.setText("6");
        jbtnNum6.setMaximumSize(null);
        jbtnNum6.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum6, gridBagConstraints);

        jbtnNum3.setText("3");
        jbtnNum3.setMaximumSize(null);
        jbtnNum3.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum3, gridBagConstraints);

        jbtnNum00.setText("00");
        jbtnNum00.setMaximumSize(null);
        jbtnNum00.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum00ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum00, gridBagConstraints);

        jbtnEnter.setText("Delete");
        jbtnEnter.setPreferredSize(new java.awt.Dimension(149, 30));
        jbtnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        jpNumPad.add(jbtnEnter, gridBagConstraints);

        jbtnClear.setText("Clear");
        jbtnClear.setPreferredSize(new java.awt.Dimension(140, 30));
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        jpNumPad.add(jbtnClear, gridBagConstraints);

        jtfNumPad.setEditable(false);
        jtfNumPad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfNumPad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfNumPad.setText("0.00");
        jtfNumPad.setMargin(new java.awt.Insets(2, 2, 2, 10));
        jtfNumPad.setPreferredSize(new java.awt.Dimension(282, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 4, 1);
        jpNumPad.add(jtfNumPad, gridBagConstraints);

        jPanel1.add(jpNumPad, "card2");

        jpPaymentButtons.setLayout(new java.awt.GridLayout(2, 2));

        jbtnBitcoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/bitcoin-coin.png"))); // NOI18N
        jbtnBitcoin.setMaximumSize(new java.awt.Dimension(129, 48));
        jbtnBitcoin.setMinimumSize(new java.awt.Dimension(129, 48));
        jbtnBitcoin.setPreferredSize(new java.awt.Dimension(129, 48));
        jbtnBitcoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBitcoinActionPerformed(evt);
            }
        });
        jpPaymentButtons.add(jbtnBitcoin);

        jbtnCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/money.png"))); // NOI18N
        jbtnCash.setMaximumSize(new java.awt.Dimension(129, 48));
        jbtnCash.setMinimumSize(new java.awt.Dimension(129, 48));
        jbtnCash.setPreferredSize(new java.awt.Dimension(129, 48));
        jbtnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCashActionPerformed(evt);
            }
        });
        jpPaymentButtons.add(jbtnCash);

        jbtnGiftCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/christmas-gift-card.png"))); // NOI18N
        jbtnGiftCard.setMaximumSize(new java.awt.Dimension(129, 48));
        jbtnGiftCard.setMinimumSize(new java.awt.Dimension(129, 48));
        jbtnGiftCard.setPreferredSize(new java.awt.Dimension(129, 48));
        jbtnGiftCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGiftCardActionPerformed(evt);
            }
        });
        jpPaymentButtons.add(jbtnGiftCard);

        jbtnCreditCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/credit-card.png"))); // NOI18N
        jbtnCreditCard.setMaximumSize(new java.awt.Dimension(187, 48));
        jbtnCreditCard.setMinimumSize(new java.awt.Dimension(187, 48));
        jbtnCreditCard.setPreferredSize(new java.awt.Dimension(129, 48));
        jbtnCreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreditCardActionPerformed(evt);
            }
        });
        jpPaymentButtons.add(jbtnCreditCard);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Payment Amount");

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setText("0.00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Split");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/ic_payment_black_48dp_1x.png"))); // NOI18N

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/ic_cancel_black_48dp_1x.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPaymentButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(26, 26, 26)
                                .addComponent(btnPay))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jpPaymentButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPay))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancel)))
                        .addGap(51, 51, 51))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNumAmt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumAmt20ActionPerformed
        cashPaymentOutput = "20.00";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumAmt20ActionPerformed

    private void jbtnNumAmt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumAmt10ActionPerformed
        cashPaymentOutput = "10.00";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumAmt10ActionPerformed

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum7ActionPerformed
        cashPaymentOutput += "7";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum7ActionPerformed

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum8ActionPerformed
        cashPaymentOutput += "8";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum8ActionPerformed

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum4ActionPerformed
        cashPaymentOutput += "4";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum4ActionPerformed

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum5ActionPerformed
        cashPaymentOutput += "5";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum5ActionPerformed

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        cashPaymentOutput += "1";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtnNumAmt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumAmt5ActionPerformed
        cashPaymentOutput = "5.00";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumAmt5ActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        cashPaymentOutput += "2";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum0ActionPerformed
        cashPaymentOutput += "0";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum0ActionPerformed

    private void jbtnNumAmtExactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumAmtExactActionPerformed
        cashPaymentOutput = lblTotal.getText();
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumAmtExactActionPerformed

    private void jbtnNumDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumDotActionPerformed
        cashPaymentOutput += ".";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumDotActionPerformed

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum9ActionPerformed
        cashPaymentOutput += "9";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum9ActionPerformed

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum6ActionPerformed
        cashPaymentOutput += "6";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum6ActionPerformed

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum3ActionPerformed
        cashPaymentOutput += "3";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum3ActionPerformed

    private void jbtnNum00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum00ActionPerformed
        cashPaymentOutput += "00";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum00ActionPerformed

    private void jbtnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnterActionPerformed
        String paymentInput = jtfNumPad.getText();
        paymentInput = paymentInput.substring(0, paymentInput.length() - 1);
        jtfNumPad.setText(paymentInput);
    }//GEN-LAST:event_jbtnEnterActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        cashPaymentOutput = "";
        jtfNumPad.setText("0.00");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnCreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreditCardActionPerformed
        showPanel("card4");
    }//GEN-LAST:event_jbtnCreditCardActionPerformed

    private void jbtnGiftCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGiftCardActionPerformed
        showPanel("card5");
    }//GEN-LAST:event_jbtnGiftCardActionPerformed

    private void jbtnBitcoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBitcoinActionPerformed
        showPanel("card3");
    }//GEN-LAST:event_jbtnBitcoinActionPerformed

    private void jbtnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCashActionPerformed
        showPanel("card2");
    }//GEN-LAST:event_jbtnCashActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    
    private void showPanel(String pnName) {
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, pnName);
    }
    private String cashPaymentOutput;
    private List<Button> products;
    private String promoCode;
    private double subtotal;
    private double promo;
    private double tax;
    private double total;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbtnBitcoin;
    private javax.swing.JButton jbtnCash;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnCreditCard;
    private javax.swing.JButton jbtnEnter;
    private javax.swing.JButton jbtnGiftCard;
    private javax.swing.JButton jbtnNum0;
    private javax.swing.JButton jbtnNum00;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnNumAmt10;
    private javax.swing.JButton jbtnNumAmt20;
    private javax.swing.JButton jbtnNumAmt5;
    private javax.swing.JButton jbtnNumAmtExact;
    private javax.swing.JButton jbtnNumDot;
    private javax.swing.JButton jbtnScanCode;
    private javax.swing.JButton jbtnSendBTC;
    private javax.swing.JLabel jlblCardNum;
    private javax.swing.JLabel jlblGiftCardNum;
    private javax.swing.JLabel jlblQRC;
    private javax.swing.JPanel jpBitcoinPayment;
    private javax.swing.JPanel jpCreditDebit;
    private javax.swing.JPanel jpGC;
    private javax.swing.JPanel jpNumPad;
    private javax.swing.JPanel jpPaymentButtons;
    private javax.swing.JRadioButton jradCredit;
    private javax.swing.JRadioButton jradDebit;
    private javax.swing.JTextField jtfBitcoinAmt;
    private javax.swing.JTextField jtfCardNum;
    private javax.swing.JTextField jtfGiftCardNum;
    private javax.swing.JTextField jtfNumPad;
    private javax.swing.JLabel lblPromo;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
