/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeshop;

import javax.swing.JOptionPane;
import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author lenovo
 */
public class PaymentPage extends javax.swing.JFrame {

    private String cashPaymentOutput;
    private String btcAddress;
    private String invoice;
    private int paymentType = 2;
    private int inputPIN;
    private double promoAmt;
    private double gcBalance;
    private double totalAmtPaid;
    private double paymentAmt;
    private double totalAmt;
    private double subTotalAmt;
    private double taxAmt;
    private double btcAmt;
    private boolean coupon;

    public PaymentPage() {
        initComponents();
        coupon = false; //promo button: ensure customer only uses 1 coupon per purchase
        cashPaymentOutput = "";
        subTotalAmt = 5.00;
        gcBalance = 100;
        taxAmt = subTotalAmt * .06; //tax must be on subtotal before discount
        totalAmt = subTotalAmt + taxAmt;

        jlblSubTotalAmt.setText(String.format("%.2f", subTotalAmt));
        jlblTaxAmt.setText(String.format("%.2f", taxAmt));
        jlblTotalAmt.setText(String.format("%.2f", totalAmt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaOrderItems = new javax.swing.JTextArea();
        jpTotals = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlblSubTotalAmt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblPromo = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblTaxAmt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblTotalAmt = new javax.swing.JLabel();
        jpSplitCheck = new javax.swing.JPanel();
        jtfTotalSplit = new javax.swing.JTextField();
        jcbSplit = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jpPaymentControls = new javax.swing.JPanel();
        jpCashPayment = new javax.swing.JPanel();
        jpNumPad = new javax.swing.JPanel();
        jbtnNumAmt20 = new javax.swing.JButton();
        jbtnNumAmt10 = new javax.swing.JButton();
        jbtnNum7 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum4 = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNumAmt5 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum0 = new javax.swing.JButton();
        jbtnNumAmtExact = new javax.swing.JButton();
        jbtnNumDot = new javax.swing.JButton();
        jbtnNum9 = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtnNum00 = new javax.swing.JButton();
        jbtnEnter = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jtfNumPad = new javax.swing.JTextField();
        jpGC = new javax.swing.JPanel();
        jlblGiftCardNum = new javax.swing.JLabel();
        jtfGiftCardNum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jpBitcoinPayment = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfBitcoinAmt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbtnSendBTC = new javax.swing.JButton();
        jbtnScanCode = new javax.swing.JButton();
        jlblQRC = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jpCreditDebit = new javax.swing.JPanel();
        jradCredit = new javax.swing.JRadioButton();
        jradDebit = new javax.swing.JRadioButton();
        jlblCardNum = new javax.swing.JLabel();
        jtfCardNum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jpPaymentButtons = new javax.swing.JPanel();
        jbtnBitcoin = new javax.swing.JButton();
        jbtnCash = new javax.swing.JButton();
        jbtnGiftCard = new javax.swing.JButton();
        jbtnCreditCard = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jpOptionButtons = new javax.swing.JPanel();
        jbtnCancel = new javax.swing.JButton();
        jbtnEditOrder = new javax.swing.JButton();
        jbtnSplitCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaOrderItems.setColumns(20);
        jtaOrderItems.setRows(5);
        jtaOrderItems.setText("Med Latte....................$4.50\nSm Mocha.....................$3.50\nLg Coffee....................$2.50");
        jScrollPane1.setViewportView(jtaOrderItems);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Subtotal");

        jlblSubTotalAmt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblSubTotalAmt.setText("0.00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Discount");

        jlblPromo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblPromo.setText("0.00");

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTax.setText("Tax");

        jlblTaxAmt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTaxAmt.setText("0.00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total");

        jlblTotalAmt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTotalAmt.setText("0.00");

        jpSplitCheck.setVisible(false);

        jcbSplit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));
        jcbSplit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSplitItemStateChanged(evt);
            }
        });
        jcbSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSplitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Split");

        javax.swing.GroupLayout jpSplitCheckLayout = new javax.swing.GroupLayout(jpSplitCheck);
        jpSplitCheck.setLayout(jpSplitCheckLayout);
        jpSplitCheckLayout.setHorizontalGroup(
            jpSplitCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSplitCheckLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbSplit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfTotalSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpSplitCheckLayout.setVerticalGroup(
            jpSplitCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSplitCheckLayout.createSequentialGroup()
                .addGroup(jpSplitCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTotalSplit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSplit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpTotalsLayout = new javax.swing.GroupLayout(jpTotals);
        jpTotals.setLayout(jpTotalsLayout);
        jpTotalsLayout.setHorizontalGroup(
            jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTotalsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpSplitCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpTotalsLayout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jlblTax)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblTotalAmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblTaxAmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblSubTotalAmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpTotalsLayout.setVerticalGroup(
            jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTotalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblSubTotalAmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPromo)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTaxAmt)
                    .addComponent(jlblTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotalAmt)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpSplitCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpPaymentControls.setLayout(new java.awt.CardLayout());

        jpCashPayment.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpNumPad.setLayout(new java.awt.GridBagLayout());

        jbtnNumAmt20.setText("20.00");
        jbtnNumAmt20.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnNumAmt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumAmt20ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumAmt20, gridBagConstraints);

        jbtnNumAmt10.setText("10.00");
        jbtnNumAmt10.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnNumAmt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumAmt10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumAmt10, gridBagConstraints);

        jbtnNum7.setText("7");
        jbtnNum7.setMaximumSize(null);
        jbtnNum7.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum7, gridBagConstraints);

        jbtnNum8.setText("8");
        jbtnNum8.setMaximumSize(null);
        jbtnNum8.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum8, gridBagConstraints);

        jbtnNum4.setText("4");
        jbtnNum4.setMaximumSize(null);
        jbtnNum4.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum4, gridBagConstraints);

        jbtnNum5.setText("5");
        jbtnNum5.setMaximumSize(null);
        jbtnNum5.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum5, gridBagConstraints);

        jbtnNum1.setText("1");
        jbtnNum1.setMaximumSize(null);
        jbtnNum1.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum1, gridBagConstraints);

        jbtnNumAmt5.setText("5.00");
        jbtnNumAmt5.setMinimumSize(new java.awt.Dimension(59, 23));
        jbtnNumAmt5.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnNumAmt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumAmt5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumAmt5, gridBagConstraints);

        jbtnNum2.setText("2");
        jbtnNum2.setMaximumSize(null);
        jbtnNum2.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum2, gridBagConstraints);

        jbtnNum0.setText("0");
        jbtnNum0.setMaximumSize(null);
        jbtnNum0.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum0, gridBagConstraints);

        jbtnNumAmtExact.setText("Exact");
        jbtnNumAmtExact.setMaximumSize(null);
        jbtnNumAmtExact.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnNumAmtExact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumAmtExactActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumAmtExact, gridBagConstraints);

        jbtnNumDot.setText(".");
        jbtnNumDot.setMaximumSize(null);
        jbtnNumDot.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNumDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNumDotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNumDot, gridBagConstraints);

        jbtnNum9.setText("9");
        jbtnNum9.setMaximumSize(null);
        jbtnNum9.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum9, gridBagConstraints);

        jbtnNum6.setText("6");
        jbtnNum6.setMaximumSize(null);
        jbtnNum6.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum6, gridBagConstraints);

        jbtnNum3.setText("3");
        jbtnNum3.setMaximumSize(null);
        jbtnNum3.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum3, gridBagConstraints);

        jbtnNum00.setText("00");
        jbtnNum00.setMaximumSize(null);
        jbtnNum00.setPreferredSize(new java.awt.Dimension(59, 23));
        jbtnNum00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum00ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpNumPad.add(jbtnNum00, gridBagConstraints);

        jbtnEnter.setText("Delete");
        jbtnEnter.setPreferredSize(new java.awt.Dimension(149, 30));
        jbtnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        jpNumPad.add(jbtnEnter, gridBagConstraints);

        jbtnClear.setText("Clear");
        jbtnClear.setPreferredSize(new java.awt.Dimension(140, 30));
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        jpNumPad.add(jbtnClear, gridBagConstraints);

        jtfNumPad.setEditable(false);
        jtfNumPad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfNumPad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfNumPad.setText("0.00");
        jtfNumPad.setMargin(new java.awt.Insets(2, 2, 2, 10));
        jtfNumPad.setPreferredSize(new java.awt.Dimension(282, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 4, 1);
        jpNumPad.add(jtfNumPad, gridBagConstraints);

        javax.swing.GroupLayout jpCashPaymentLayout = new javax.swing.GroupLayout(jpCashPayment);
        jpCashPayment.setLayout(jpCashPaymentLayout);
        jpCashPaymentLayout.setHorizontalGroup(
            jpCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCashPaymentLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jpNumPad, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpCashPaymentLayout.setVerticalGroup(
            jpCashPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCashPaymentLayout.createSequentialGroup()
                .addComponent(jpNumPad, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpPaymentControls.add(jpCashPayment, "card2");

        jpGC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpGC.setVisible(false);

        jlblGiftCardNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblGiftCardNum.setText("Enter Gift Card Number");

        jtfGiftCardNum.setText(" ");

        jButton1.setText("Check Balance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpGCLayout = new javax.swing.GroupLayout(jpGC);
        jpGC.setLayout(jpGCLayout);
        jpGCLayout.setHorizontalGroup(
            jpGCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGCLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jpGCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGCLayout.createSequentialGroup()
                        .addComponent(jlblGiftCardNum)
                        .addGap(18, 18, 18)
                        .addComponent(jtfGiftCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGCLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(71, 71, 71))))
        );
        jpGCLayout.setVerticalGroup(
            jpGCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGCLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jpGCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblGiftCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGiftCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jpPaymentControls.add(jpGC, "card5");

        jpBitcoinPayment.setVisible(false);
        jpBitcoinPayment.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Send");

        jLabel9.setText("to");

        jtfBitcoinAmt.setText("                 ");

        jLabel12.setText("BTC");

        jLabel13.setText("23480yskjuLXKueAVck123l032");

        jbtnSendBTC.setText("OK");
        jbtnSendBTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSendBTCActionPerformed(evt);
            }
        });

        jbtnScanCode.setText("Scan Code");
        jbtnScanCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnScanCodeActionPerformed(evt);
            }
        });

        jlblQRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/QRC.png"))); // NOI18N
        jlblQRC.setText(" ");
        jlblQRC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("1 BTC = $1000");

        javax.swing.GroupLayout jpBitcoinPaymentLayout = new javax.swing.GroupLayout(jpBitcoinPayment);
        jpBitcoinPayment.setLayout(jpBitcoinPaymentLayout);
        jpBitcoinPaymentLayout.setHorizontalGroup(
            jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblQRC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                        .addComponent(jtfBitcoinAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)))
                .addGap(24, 24, 24))
            .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jbtnScanCode, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSendBTC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBitcoinPaymentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jpBitcoinPaymentLayout.setVerticalGroup(
            jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                        .addContainerGap(52, Short.MAX_VALUE)
                        .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtfBitcoinAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9))
                        .addGap(97, 97, 97))
                    .addGroup(jpBitcoinPaymentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblQRC, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpBitcoinPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnSendBTC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnScanCode, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel11)
                .addGap(5, 5, 5))
        );

        jpPaymentControls.add(jpBitcoinPayment, "card3");

        jpCreditDebit.setVisible(false);
        jpCreditDebit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jradCredit);
        jradCredit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jradCredit.setSelected(true);
        jradCredit.setText("Credit");

        buttonGroup1.add(jradDebit);
        jradDebit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jradDebit.setText("Debit");

        jlblCardNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblCardNum.setText("Card Number");

        jtfCardNum.setText(" ");
        jtfCardNum.setMinimumSize(new java.awt.Dimension(6, 24));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Expiration Date");

        jTextField1.setPreferredSize(new java.awt.Dimension(6, 24));

        jLabel14.setText("mm/yy");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("CCV");

        jTextField2.setPreferredSize(new java.awt.Dimension(6, 24));

        javax.swing.GroupLayout jpCreditDebitLayout = new javax.swing.GroupLayout(jpCreditDebit);
        jpCreditDebit.setLayout(jpCreditDebitLayout);
        jpCreditDebitLayout.setHorizontalGroup(
            jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreditDebitLayout.createSequentialGroup()
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCreditDebitLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jradCredit)
                        .addGap(37, 37, 37)
                        .addComponent(jradDebit))
                    .addGroup(jpCreditDebitLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCardNum))
                        .addGap(18, 18, 18)
                        .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpCreditDebitLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addComponent(jtfCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jpCreditDebitLayout.setVerticalGroup(
            jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreditDebitLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradDebit)
                    .addComponent(jradCredit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCardNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreditDebitLayout.createSequentialGroup()
                        .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreditDebitLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jpCreditDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(42, 42, 42))
        );

        jpPaymentControls.add(jpCreditDebit, "card4");

        jpPaymentButtons.setLayout(new java.awt.GridBagLayout());

        jbtnBitcoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/bitcoin.png"))); // NOI18N
        jbtnBitcoin.setText("Bitcoin");
        jbtnBitcoin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnBitcoin.setMaximumSize(new java.awt.Dimension(129, 48));
        jbtnBitcoin.setMinimumSize(new java.awt.Dimension(129, 48));
        jbtnBitcoin.setPreferredSize(new java.awt.Dimension(129, 48));
        jbtnBitcoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnBitcoinMousePressed(evt);
            }
        });
        jbtnBitcoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBitcoinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpPaymentButtons.add(jbtnBitcoin, gridBagConstraints);

        jbtnCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/cash.png"))); // NOI18N
        jbtnCash.setText("Cash");
        jbtnCash.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnCash.setMaximumSize(new java.awt.Dimension(129, 48));
        jbtnCash.setMinimumSize(new java.awt.Dimension(129, 48));
        jbtnCash.setPreferredSize(new java.awt.Dimension(129, 48));
        jbtnCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnCashMousePressed(evt);
            }
        });
        jbtnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCashActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpPaymentButtons.add(jbtnCash, gridBagConstraints);

        jbtnGiftCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/giftcard.png"))); // NOI18N
        jbtnGiftCard.setText("Gift Card");
        jbtnGiftCard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnGiftCard.setMaximumSize(new java.awt.Dimension(129, 48));
        jbtnGiftCard.setMinimumSize(new java.awt.Dimension(129, 48));
        jbtnGiftCard.setPreferredSize(new java.awt.Dimension(129, 48));
        jbtnGiftCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnGiftCardMousePressed(evt);
            }
        });
        jbtnGiftCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGiftCardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpPaymentButtons.add(jbtnGiftCard, gridBagConstraints);

        jbtnCreditCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageRes/creditcard.png"))); // NOI18N
        jbtnCreditCard.setText("Credit/Debit Card");
        jbtnCreditCard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnCreditCard.setMaximumSize(new java.awt.Dimension(187, 48));
        jbtnCreditCard.setMinimumSize(new java.awt.Dimension(187, 48));
        jbtnCreditCard.setPreferredSize(new java.awt.Dimension(129, 48));
        jbtnCreditCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnCreditCardMousePressed(evt);
            }
        });
        jbtnCreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreditCardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jpPaymentButtons.add(jbtnCreditCard, gridBagConstraints);

        jbtnPay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });

        jpOptionButtons.setLayout(new java.awt.GridBagLayout());

        jbtnCancel.setText("Cancel");
        jbtnCancel.setMaximumSize(new java.awt.Dimension(81, 23));
        jbtnCancel.setMinimumSize(new java.awt.Dimension(81, 23));
        jbtnCancel.setPreferredSize(new java.awt.Dimension(81, 23));
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jpOptionButtons.add(jbtnCancel, gridBagConstraints);

        jbtnEditOrder.setText("Edit Order");
        jbtnEditOrder.setMaximumSize(new java.awt.Dimension(81, 25));
        jbtnEditOrder.setMinimumSize(new java.awt.Dimension(81, 25));
        jbtnEditOrder.setPreferredSize(new java.awt.Dimension(80, 23));
        jbtnEditOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditOrderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jpOptionButtons.add(jbtnEditOrder, gridBagConstraints);

        jbtnSplitCheck.setText("Split Check");
        jbtnSplitCheck.setMaximumSize(new java.awt.Dimension(81, 23));
        jbtnSplitCheck.setMinimumSize(new java.awt.Dimension(81, 23));
        jbtnSplitCheck.setPreferredSize(new java.awt.Dimension(81, 23));
        jbtnSplitCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSplitCheckActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jpOptionButtons.add(jbtnSplitCheck, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jpPaymentButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jpPaymentControls, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpTotals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(jbtnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jpOptionButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpOptionButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jpTotals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpPaymentButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jpPaymentControls, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbtnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBitcoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBitcoinActionPerformed
        double usdAmt = Double.parseDouble(jlblTotalAmt.getText());
        btcAmt = usdAmt / 1000;
        btcAddress = "23480yskjuLXKueAVck123l032";

        showPanel("card3");
        paymentType = 3;
        jtfBitcoinAmt.setText(String.format("%.6f", btcAmt));
    }//GEN-LAST:event_jbtnBitcoinActionPerformed

    private void jbtnBitcoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBitcoinMousePressed
        jbtnBitcoin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnCash.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        jbtnGiftCard.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        jbtnCreditCard.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
    }//GEN-LAST:event_jbtnBitcoinMousePressed

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        cashPaymentOutput += "1";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        cashPaymentOutput = "";
        jtfNumPad.setText("0.00");
        jtfNumPad.setForeground(Color.BLACK);
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        cashPaymentOutput += "2";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum3ActionPerformed
        cashPaymentOutput += "3";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum3ActionPerformed

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum4ActionPerformed
        cashPaymentOutput += "4";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum4ActionPerformed

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum5ActionPerformed
        cashPaymentOutput += "5";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum5ActionPerformed

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum6ActionPerformed
        cashPaymentOutput += "6";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum6ActionPerformed

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum7ActionPerformed
        cashPaymentOutput += "7";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum7ActionPerformed

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum8ActionPerformed
        cashPaymentOutput += "8";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum8ActionPerformed

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum9ActionPerformed
        cashPaymentOutput += "9";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum9ActionPerformed

    private void jbtnNumAmt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumAmt10ActionPerformed
        cashPaymentOutput = "10.00";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumAmt10ActionPerformed

    private void jbtnNumAmt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumAmt20ActionPerformed
        cashPaymentOutput = "20.00";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumAmt20ActionPerformed

    private void jbtnNum00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum00ActionPerformed
        cashPaymentOutput += "00";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum00ActionPerformed

    private void jbtnNumDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumDotActionPerformed
        cashPaymentOutput += ".";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumDotActionPerformed

    private void jbtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum0ActionPerformed
        cashPaymentOutput += "0";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNum0ActionPerformed

    private void jbtnNumAmtExactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumAmtExactActionPerformed
        cashPaymentOutput = jlblTotalAmt.getText();
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumAmtExactActionPerformed

    private void jbtnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCashActionPerformed
        paymentType = 2;
        showPanel("card2");
    }//GEN-LAST:event_jbtnCashActionPerformed

    private void jbtnGiftCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGiftCardActionPerformed
        paymentType = 5;
        showPanel("card5");
    }//GEN-LAST:event_jbtnGiftCardActionPerformed

    private void jbtnCashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCashMousePressed
        jbtnCash.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnBitcoin.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        jbtnGiftCard.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        jbtnCreditCard.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());

    }//GEN-LAST:event_jbtnCashMousePressed

    private void jbtnCreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreditCardActionPerformed
        showPanel("card4");
        paymentType = 4;
    }//GEN-LAST:event_jbtnCreditCardActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        boolean paid = false;
        String newTotal;
        double change = 0;
        totalAmtPaid = 0;
        totalAmt = Double.parseDouble(jlblTotalAmt.getText());

        if (jpSplitCheck.isVisible() == true) {
            paymentAmt = Double.parseDouble(jtfTotalSplit.getText());
        } else {
            paymentAmt = totalAmt;
        }

        invoice = String.format("%s%nTotal.............................$%s", jtaOrderItems.getText(), jlblTotalAmt.getText());
        switch (paymentType) {
            case 2:
                paymentAmt = Double.parseDouble(jtfNumPad.getText());
                totalAmtPaid += paymentAmt;
                change = paymentAmt - totalAmt;

                if (change >= 0) {
                    invoice += String.format("\n Amount Tendered:         %.2f", totalAmtPaid);
                    invoice += String.format("\n Change:                 %.2f", change);
                    paid = true;
                } else {
                    totalAmt -= paymentAmt;
                    newTotal = String.format("%.2f", totalAmt);
                    jlblTotalAmt.setText(newTotal);
                }
                break;

            case 3: //bitcoin... see case 6
                String output = String.format("Please scan code or \nSend %.5f BTC \nto %s", btcAmt, btcAddress);
                JOptionPane.showMessageDialog(null, output);
                break;
            case 4: //credit card
                    if (jradCredit.isSelected()) {  
                    totalAmtPaid += paymentAmt;
                    change = paymentAmt - totalAmt;
                    if (change >= 0) {     
                    invoice += String.format("\n Amount Applied:         $%s", jlblTotalAmt.getText());
                    invoice += String.format("\n Change:                 $0.00");
                    paid = true;
                } else {
                    totalAmt -= paymentAmt;
                    newTotal = String.format("%.2f", totalAmt);
                    jlblTotalAmt.setText(newTotal);
                }
                    }else {
                    inputPIN = Integer.parseInt(JOptionPane.showInputDialog("Enter PIN"));
                    //check to make sure inputPIN matches actual PIN
                    totalAmtPaid += paymentAmt;
                    change = paymentAmt - totalAmt;
                    if (change >= 0) {     
                    invoice += String.format("\n Amount Applied:         $%s", jlblTotalAmt.getText());
                    invoice += String.format("\n Change:                 $0.00");
                    paid = true;
                    }
                    
                      }
                
                
              

                //credit card
                break;
            case 5: //gift card
                paymentAmt = totalAmt;
                change = gcBalance - totalAmt;
                invoice += String.format("\n GC Applied:         $%s", jlblTotalAmt.getText());
                invoice += String.format("\n Remaining Balance:                 $%.2f", change);
                paid = true;
                break;

            case 6: //bitcoin OK button or Scan pressed
                
                invoice += String.format("\n BTC Received                  %.7f", btcAmt);
                invoice += String.format("\n USD Applied                     %.2f", totalAmt);
                paid = true;
                break;
        }

        if (paid) {
            JOptionPane.showMessageDialog(null, invoice);
        }

    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnNumAmt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNumAmt5ActionPerformed
        cashPaymentOutput = "5.00";
        jtfNumPad.setText(cashPaymentOutput);
    }//GEN-LAST:event_jbtnNumAmt5ActionPerformed

    private void jbtnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnterActionPerformed
        String paymentInput = jtfNumPad.getText();
        paymentInput = paymentInput.substring(0, paymentInput.length() - 1);
        jtfNumPad.setText(paymentInput);
    }//GEN-LAST:event_jbtnEnterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String showBalance = String.format("Gift Card Balance: %.2f", gcBalance);
        JOptionPane.showMessageDialog(null, showBalance);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnSendBTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSendBTCActionPerformed
        paymentType = 6;
        jbtnPayActionPerformed(evt);
    }//GEN-LAST:event_jbtnSendBTCActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        //delete entire order and return to MainPage 
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnEditOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditOrderActionPerformed
//keep order items and return to Mainpage       
    }//GEN-LAST:event_jbtnEditOrderActionPerformed

    private void jbtnGiftCardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnGiftCardMousePressed
        jbtnGiftCard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnCash.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        jbtnBitcoin.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        jbtnCreditCard.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
    }//GEN-LAST:event_jbtnGiftCardMousePressed

    private void jbtnCreditCardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCreditCardMousePressed
        jbtnCreditCard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnCash.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        jbtnGiftCard.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        jbtnBitcoin.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
    }//GEN-LAST:event_jbtnCreditCardMousePressed

    private void jbtnScanCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnScanCodeActionPerformed
        paymentType = 6;
        jbtnPayActionPerformed(evt);

    }//GEN-LAST:event_jbtnScanCodeActionPerformed

    private void jcbSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSplitActionPerformed

        int selection = jcbSplit.getSelectedIndex();
    }//GEN-LAST:event_jcbSplitActionPerformed

    private void jcbSplitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSplitItemStateChanged
int selection = 0;
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
       selection = jcbSplit.getSelectedIndex();
 }
       
        switch (selection) {
            case 0:
                paymentAmt = totalAmt / 2;
                break;
            case 1:
                paymentAmt = totalAmt / 3;
                break;
            case 2:
                paymentAmt = totalAmt / 4;
                break;
            case 3:
                paymentAmt = totalAmt / 5;
                break;
        }
        jtfTotalSplit.setText(String.format("%.2f", paymentAmt));


    }//GEN-LAST:event_jcbSplitItemStateChanged

    private void jbtnSplitCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSplitCheckActionPerformed
        jpSplitCheck.setVisible(true);
        paymentAmt = totalAmt / 2;
        jtfTotalSplit.setText(String.format("%.2f", paymentAmt));
    }//GEN-LAST:event_jbtnSplitCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentPage().setVisible(true);
            }
        });
    }

    private void showPanel(String pnName) {
        CardLayout layout = (CardLayout) jpPaymentControls.getLayout();
        layout.show(jpPaymentControls, pnName);
    }
    // private ImageIcon icon1 = new ImageIcon("src/ImageRes/cash.png");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtnBitcoin;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnCash;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnCreditCard;
    private javax.swing.JButton jbtnEditOrder;
    private javax.swing.JButton jbtnEnter;
    private javax.swing.JButton jbtnGiftCard;
    private javax.swing.JButton jbtnNum0;
    private javax.swing.JButton jbtnNum00;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnNumAmt10;
    private javax.swing.JButton jbtnNumAmt20;
    private javax.swing.JButton jbtnNumAmt5;
    private javax.swing.JButton jbtnNumAmtExact;
    private javax.swing.JButton jbtnNumDot;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnScanCode;
    private javax.swing.JButton jbtnSendBTC;
    private javax.swing.JButton jbtnSplitCheck;
    private javax.swing.JComboBox<String> jcbSplit;
    private javax.swing.JLabel jlblCardNum;
    private javax.swing.JLabel jlblGiftCardNum;
    private javax.swing.JLabel jlblPromo;
    private javax.swing.JLabel jlblQRC;
    private javax.swing.JLabel jlblSubTotalAmt;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTaxAmt;
    private javax.swing.JLabel jlblTotalAmt;
    private javax.swing.JPanel jpBitcoinPayment;
    private javax.swing.JPanel jpCashPayment;
    private javax.swing.JPanel jpCreditDebit;
    private javax.swing.JPanel jpGC;
    private javax.swing.JPanel jpNumPad;
    private javax.swing.JPanel jpOptionButtons;
    private javax.swing.JPanel jpPaymentButtons;
    private javax.swing.JPanel jpPaymentControls;
    private javax.swing.JPanel jpSplitCheck;
    private javax.swing.JPanel jpTotals;
    private javax.swing.JRadioButton jradCredit;
    private javax.swing.JRadioButton jradDebit;
    private javax.swing.JTextArea jtaOrderItems;
    private javax.swing.JTextField jtfBitcoinAmt;
    private javax.swing.JTextField jtfCardNum;
    private javax.swing.JTextField jtfGiftCardNum;
    private javax.swing.JTextField jtfNumPad;
    private javax.swing.JTextField jtfTotalSplit;
    // End of variables declaration//GEN-END:variables
}
